### ISSUE TITLE
Occasional assertion fail in pthreads on startup

### ISSUE THREAD

**Issue by WPettersson** [WPettersson/Civ6Issues#1]
Civ6 seems to sometimes crash when starting up. This doesn't always happen, but has happened a few times. The output from Steam in the console is below. I checked, and Civ5 gives the exact same errors regarding LD_PRELOAD and still runs fine (and the shift-tab overlay works fine). For what it's worth, that dynamic library is identified as gameoverlayrenderer.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=33ffb0884de385f7b0135e7949a5daf72fc3cf4c, not stripped
```
>>> Adding process 11217 for game ID 289070
Setting breakpad minidump AppID = 289070
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197993464199 [API loaded no]
ERROR: ld.so: object '/home/enigma/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/enigma/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
env: ‘lspci’: No such file or directory
ERROR: ld.so: object '/home/enigma/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/enigma/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 11221 for game ID 289070
env: ‘lspci’: No such file or directory
>>> Adding process 11222 for game ID 289070
Civ6: ../nptl/pthread_mutex_lock.c:352: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust' failed.
Game removed: AppID 289070 "Sid Meier's Civilization VI", ProcID 11217
```

**Comment by WPettersson** [comment]
I found a backtrace. I would attach the coredump as well, but it's 260MB, so maybe not. 
```
#0 0x00007f11e0897107 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1 0x00007f11e089855a in __GI_abort () at abort.c:89
#2 0x00007f11e08901ad in __assert_fail_base (fmt=0x7f11e09c7828 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
assertion=assertion@entry=0x7f11e173bc60 "INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust",
file=file@entry=0x7f11e173bba8 "../nptl/pthread_mutex_lock.c", line=line@entry=352,
function=function@entry=0x7f11e173bd10 <__PRETTY_FUNCTION__.9194> "__pthread_mutex_lock_full") at assert.c:92
#3 0x00007f11e0890262 in __GI___assert_fail (
assertion=assertion@entry=0x7f11e173bc60 "INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust",
file=file@entry=0x7f11e173bba8 "../nptl/pthread_mutex_lock.c", line=line@entry=352,
function=function@entry=0x7f11e173bd10 <__PRETTY_FUNCTION__.9194> "__pthread_mutex_lock_full") at assert.c:101
#4 0x00007f11e173296a in __pthread_mutex_lock_full (mutex=0x7f11c4f5ca00) at ../nptl/pthread_mutex_lock.c:352
#5 0x0000000001c008ba in Firaxis::Thread::SuspendWait() ()
#6 0x0000000001bff8e1 in Firaxis::Thread::StartRoutine(void*) ()
#7 0x00007f11e1730444 in start_thread (arg=0x7f11c903d700) at pthread_create.c:333
#8 0x00007f11e094b5ad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by WPettersson** [comment]
I think I worked out how to trigger this. I run a 4-core machine, and if run some other CPU-intensive tasks so that I don't have much spare processor time, the crash seems to reliably happen.
